# unbound settings
unbound_num_threads: 2
unbound_cache_slabs: 2
unbound_msg_cache: 256m
unbound_rrset_cache: 512m
unbound_socket_buffer: 4m
unbound_outgoing_range: 450
unbound_num_queries: 225
unbound_tcp_keepalive: 0
unbound_tls_interfaces:
  - "0.0.0.0"
  - "::0"
unbound_access_control:
  - "0.0.0.0/0 allow"
  - "::0/0 allow"
# unbound exporter settings
unbound_etc: /etc/unbound
unbound_exporter_repo: https://github.com/kumina/unbound_exporter.git
unbound_exporter_commit: c5af67df1c4e8466ced5b14b8c331c0add01878c
unbound_exporter_path: /opt/unbound_exporter
