---
- hosts: all
  roles:
    - role: basics
      tags: basics

- hosts: unbound
  roles:
    - role: unbound
      tags: unbound

- hosts: all
  roles:
    - role: tor
      tags: tor

- hosts: tor_exporter
  roles:
    - role: tor_exporter
      tags: tor_exporter

- hosts: tor_snowflake
  roles:
    - role: snowflake
      tags: snowflake
