---
- hosts: tor_relays
  roles:
    - role: basics
      tags: basics

- hosts: tor_unbound
  roles:
    - role: unbound
      tags: unbound

- hosts: tor_relays
  roles:
    - role: tor
      tags: tor

- hosts: tor_exporter
  roles:
    - role: tor_exporter
      tags: tor_exporter

- hosts: tor_snowflake
  roles:
    - role: basics
      tags: basics
    - role: tor
      tags: tor
    - role: snowflake
      tags: snowflake
