---
- hosts: all
  roles:
    - role: basics
      tags: basics

- hosts: tor_relays
  roles:
    - role: unbound
      tags: unbound
      when: unbound and tor_instances_exit

- hosts: all
  roles:
    - role: tor
      tags: tor

- hosts: tor_relays
  roles:
    - role: tor-exporter
      tags: tor-exporter
      when: tor_exporter
    - role: nginx
      tags: nginx
      when: nginx and (tor_exporter or tor_exit_notice and tor_instances_exit)
    - role: tor-exit-notice
      tags: tor-exit-notice
      when: tor_exit_notice and tor_instances_exit

- hosts: tor_snowflake
  roles:
    - role: snowflake
      tags: snowflake
