---
- hosts: all
  roles:
    - role: alxndr42.commons.basics
      tags: basics
      when: basics

- hosts: tor_relays
  roles:
    - role: unbound
      tags: unbound
      when: unbound and tor_instances_exit

- hosts: all
  roles:
    - role: tor
      tags: tor

- hosts: tor_relays
  roles:
    - role: alxndr42.commons.nginx
      tags: nginx
      when: tor_exit_notice and tor_instances_exit
    - role: tor-exit-notice
      tags: tor-exit-notice
      when: tor_exit_notice and tor_instances_exit
    - role: tor-exporter
      tags: tor-exporter
      when: tor_exporter

- hosts: tor_snowflake
  roles:
    - role: snowflake
      tags: snowflake
