---
- hosts: all
  roles:
    - role: basics
      tags: basics

- hosts: unbound
  roles:
    - role: unbound
      tags: unbound

- hosts: all
  roles:
    - role: tor
      tags: tor

- hosts: tor_exporter
  roles:
    - role: tor-exporter
      tags: tor-exporter

- hosts: tor_snowflake
  roles:
    - role: snowflake
      tags: snowflake

- hosts: nginx
  roles:
    - role: nginx
      tags: nginx
