---
- name: template {{ item.name }} exporter
  template:
    src: tor_exporter.service
    dest: /etc/systemd/system/tor_exporter_{{ item.name }}.service
  register: config

- name: enable {{ item.name }} exporter
  systemd:
    name: tor_exporter_{{ item.name }}
    state: started
    enabled: yes
    daemon_reload: yes

- name: restart {{ item.name }} exporter
  systemd:
    name: tor_exporter_{{ item.name }}
    state: restarted
  when: config.changed
