---
- name: install required packages
  apt:
    name: golang
    cache_valid_time: 86400

- name: clone exporter
  git:
    repo: https://github.com/kumina/unbound_exporter.git
    dest: "{{ unbound_exporter_path }}"
    version: "{{ unbound_exporter_commit }}"
  register: git

- name: get dependencies
  command: go get -d
  args:
    chdir: "{{ unbound_exporter_path }}"
  when: git.changed

- name: build exporter
  command: go build
  args:
    chdir: "{{ unbound_exporter_path }}"
  when: git.changed
  notify: restart exporter

- name: template service
  template:
    src: unbound_exporter.service
    dest: /etc/systemd/system/
  notify: restart exporter

- name: enable service
  systemd:
    name: unbound_exporter
    enabled: yes
    daemon_reload: yes
