---
- name: install packages
  apt:
    name:
      - unbound

- name: copy static configuration
  copy:
    src: "{{ item }}"
    dest: /etc/unbound/unbound.conf.d/
  with_items:
    - control-enable.conf
    - extended-statistics.conf
  notify: restart unbound

- name: template performance.conf
  template:
    src: performance.conf
    dest: /etc/unbound/unbound.conf.d/
  notify: restart unbound

- name: template dns-over-tls.conf
  template:
    src: dns-over-tls.conf
    dest: /etc/unbound/unbound.conf.d/
  notify: restart unbound
  when: unbound_tls_service_crt is defined

- include_tasks: install-exporter.yml
  when: unbound_exporter_address is defined
