---
- name: install required packages
  ansible.builtin.apt:
    name: "{{ snowflake_required_packages }}"
    cache_valid_time: 86400

- name: clone snowflake
  ansible.builtin.git:
    repo: "https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake.git"
    dest: "{{ snowflake_path }}"
    version: "{{ snowflake_commit }}"
  register: git

- name: build snowflake
  ansible.builtin.command: "{{ snowflake_build_command }}"
  args:
    chdir: "{{ snowflake_path }}/proxy"
  when: git.changed

- name: copy snowflake
  ansible.builtin.copy:
    src: "{{ snowflake_path }}/proxy/proxy"
    dest: /usr/local/bin/snowflake
    remote_src: yes
    mode: 0755
  when: git.changed
  notify: restart snowflake

- name: template snowflake.service
  ansible.builtin.template:
    src: snowflake.service
    dest: /etc/systemd/system
  notify: restart snowflake

- name: enable snowflake service
  ansible.builtin.systemd:
    name: snowflake
    enabled: yes
    daemon_reload: yes
