---
node_exporter_url: https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz
node_exporter_sha256: "344bd4c0bbd66ff78f14486ec48b89c248139cdd485e992583ea30e89e0e5390"
node_exporter_path: /opt/node_exporter
node_exporter_address: "localhost:9100"
node_exporter_options: []
node_exporter_user: nobody
tor_exporter_url: https://github.com/atx/prometheus-tor_exporter/releases/download/v0.4/prometheus-tor-exporter_0.4_all.deb
tor_exporter_sha256: "18ff114b31dd26262872462f09ba12e81d33c1271468f56fe565fbe32a18f10e"
tor_exporter_instances:
  - name: default
    control_socket: /var/run/tor/control
    user: debian-tor
